# Generated by Django 5.2.10 on 2026-03-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patientprofile_biometric_enabled_patientprofile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
