# Generated by Django 5.2.10 on 2026-03-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_securityalert_systemconfig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalprofile',
            old_name='medical_license_number',
            new_name='mdcn_number',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='medical_license_document',
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='category',
            field=models.CharField(choices=[('PRIVATE', 'Private Hospital'), ('PUBLIC', 'Public General Hospital'), ('PHARMACY', 'Pharmacy'), ('DIAGNOSTIC', 'Diagnostic Lab'), ('PRIMARY', 'Primary Health Centre')], default='PRIVATE', max_length=50),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='director_license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='director_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='hefamaa_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='hefamaa_license',
            field=models.FileField(blank=True, null=True, upload_to='hospitals/hefamaa/'),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='letter_of_intent',
            field=models.FileField(blank=True, null=True, upload_to='hospitals/loi/'),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='hospitals/address_proof/'),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='tin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='cac_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
