# Generated by Django 5.2.10 on 2026-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_medical_license_number_hospitalprofile_mdcn_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='record_type',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('PDF', 'PDF'), ('EVENT', 'Manual Health Event')], max_length=10),
        ),
    ]
