# Generated by Django 5.2.10 on 2026-03-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_healthrecord_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
