# Generated by Django 5.2.10 on 2026-03-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_healthrecord_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='health_records/'),
        ),
    ]
